###########################
# PORTS
# 1587: Email Service
# 3306: User Database
# 3307: Inventory Database
# 8080: User LB
# 8081: Admin LB
# 8082: User Service
# 8083: Inventory Service
# 8084: IDP Service
# 9600: User BFF
# 9601: User BFF2
# 9602: Admin BFF
# 9603: Admin BFF2 
###########################

services: 
  user-db:
    image: mysql:9.3
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: userpassword
    ports:
      - 3306:3306
    volumes:
      - user-db-data:/var/lib/mysql
      - ./db_user/create-script.sql:/docker-entrypoint-initdb.d/create-script.sql
    networks:
      user-network:
      admin-network:

  inventory-db:
    image: mysql:9.3
    container_name: inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: inventorypassword
    ports:
      - 3307:3306
    volumes:
      - inventory-db-data:/var/lib/mysql
      - ./db_inventory/create-script.sql:/docker-entrypoint-initdb.d/create-script.sql
    networks:
      user-network:
      admin-network:

  user-service:
    build:
      context: .
      dockerfile: user-services/Dockerfile
    image: user-service:latest
    container_name: user-service
    ports:
      - 8082:8080
    networks:
      user-network:
      admin-network:

  inventory-service:
    build:
      context: .
      dockerfile: inventory-services/Dockerfile
    image: inventory-service:latest
    container_name: inventory-service
    ports:
      - 8083:8080
    networks:
      user-network:
      admin-network:

  user-bff1:
    build:
      context: .
      dockerfile: bff-user/Dockerfile
    image: user-bff:latest
    container_name: user-bff1
    ports:
      - 9600:9600
    networks:
      user-network:

  user-bff2:
    image: user-bff:latest
    container_name: user-bff2
    ports:
      - 9601:9600
    networks:
      user-network:
    depends_on:
      - user-bff1

  admin-bff1:
    build:
      context: .
      dockerfile: bff-admin/Dockerfile
    image: admin-bff:latest
    container_name: admin-bff1
    ports:
      - 9602:9600
    networks:
      admin-network:

  admin-bff2:
    image: admin-bff:latest
    container_name: admin-bff2
    ports:
      - 9603:9600
    networks:
      admin-network:
    depends_on:
      - admin-bff1

  user-lb:
    image: nginx:latest
    container_name: user-lb
    ports:
      - 8080:80
    networks:
      user-network:
    depends_on:
      - user-bff1
      - user-bff2
    volumes:
      - ./nginx/user-lb.conf:/etc/nginx/conf.d/default.conf

  admin-lb:
    image: nginx:latest
    container_name: admin-lb
    ports:
      - 8081:80
    networks:
      admin-network:
    depends_on:
      - admin-bff1
      - admin-bff2
    volumes:
      - ./nginx/admin-lb.conf:/etc/nginx/conf.d/default.conf

  idp-service:
    build:
      context: .
      dockerfile: idp-services/Dockerfile
    image: idp-service:latest
    container_name: idp-service
    ports:
      - 8084:8080
    environment:
      JWT_SECRET: "super-secret-jwt-key"
    networks:
      user-network:
      admin-network:

  email-service:
    image: boky/postfix:latest
    container_name: email-service
    restart: always
    ports:
      - "1587:587"
    environment:
      ALLOWED_SENDER_DOMAINS: wit.edu
      HOSTNAME: mail.sneaker.local
    volumes:
      - postfix_data:/var/spool/postfix

volumes:
  user-db-data:
  inventory-db-data:
  postfix_data:

networks:
  user-network:
  admin-network: