services:
  user-service:
    build:
      context: ..
      dockerfile: user-services/Dockerfile
    container_name: user-service
    ports:
      - 8082:8080
    networks:
      - user-network
      - admin-network
networks:
  user-network:
  admin-network: